# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
jwt:
  # 签发人
  issuer: monthwolf
  # 秘钥
  secret: WFa7kgmmqjONa9piuuxT+q3ZknT50wwT6Hty5c+lHVBeJ0bBUd3P7FkBaTWXICtlK+0aX//JuDWiST6lbubGOQ==