# 应用服务 WEB 访问端口
server:
  port: 8080
#=================================================================
# log 日志
#=================================================================
logging:
  config: classpath:logback-weblog.xml

